"""Generate a preliminary design brief from CEA + sizing helpers."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from rocketcae.geometry import NozzleGeometry
from rocketcae.models import EngineResult
from rocketcae.sizing import BurnProfile, StageSizing


def format_design_brief(
    title: str,
    cea: EngineResult,
    sizing: StageSizing | None = None,
    burn: BurnProfile | None = None,
    nozzle: NozzleGeometry | None = None,
    tank_volumes: dict | None = None,
    comparisons: list[dict] | None = None,
    extra_notes: str = "",
) -> str:
    """Markdown design brief for engineers / notebooks / GUI download."""
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"_Generated by RocketCAE {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_")
    lines.append("")
    lines.append("## Disclaimer")
    lines.append("")
    lines.append(
        "Preliminary **chemical-equilibrium** and **ideal rocket-equation** estimates only. "
        "Not certified flight design. Validate with test data and full engineering analysis."
    )
    lines.append("")

    lines.append("## CEA performance (equilibrium)")
    lines.append("")
    if not cea.success:
        lines.append(f"**CEA failed:** {cea.message}")
    else:
        inp = cea.inputs
        lines.append(f"| Quantity | Value |")
        lines.append(f"|----------|-------|")
        lines.append(f"| Fuel / Oxidizer | `{inp.fuel}` / `{inp.oxidizer}` |")
        lines.append(f"| O/F (mass) | {inp.of_ratio:.4f} |")
        lines.append(f"| Pc | {cea.pc_bar:.3f} bar |")
        lines.append(f"| Ae/At | {cea.area_ratio:.3f} |")
        lines.append(f"| Tc | {cea.tc_k:.1f} K |")
        lines.append(f"| c* | {cea.cstar_m_s:.1f} m/s |")
        lines.append(f"| Cf | {cea.cf:.4f} |")
        lines.append(f"| Isp | {cea.isp_s:.2f} s ({cea.isp_m_s:.1f} m/s) |")
        lines.append(f"| Isp vac | {cea.isp_vac_s:.2f} s ({cea.isp_vac_m_s:.1f} m/s) |")
        if cea.density_isp_s is not None:
            lines.append(f"| Density-Isp proxy | {cea.density_isp_s:.3f} |")
    lines.append("")

    if sizing and sizing.success:
        lines.append("## Ideal stage sizing (Δv)")
        lines.append("")
        lines.append(f"| Quantity | Value |")
        lines.append(f"|----------|-------|")
        lines.append(f"| Target Δv | {sizing.delta_v_m_s:.0f} m/s |")
        lines.append(f"| Isp used | {sizing.isp_s:.2f} s |")
        lines.append(f"| Payload | {sizing.payload_kg:.2f} kg |")
        lines.append(f"| Structural fraction | {sizing.structural_fraction:.3f} |")
        lines.append(f"| Mass ratio m0/mf | {sizing.mass_ratio:.4f} |")
        lines.append(f"| Propellant mass | {sizing.propellant_mass_kg:.2f} kg |")
        lines.append(f"| Inert mass | {sizing.inert_mass_kg:.2f} kg |")
        lines.append(f"| Gross mass | {sizing.gross_mass_kg:.2f} kg |")
        lines.append(f"| Propellant mass fraction | {sizing.propellant_mass_fraction:.3f} |")
        lines.append("")

    if burn and burn.success:
        lines.append("## Constant-thrust burn")
        lines.append("")
        lines.append(f"| Quantity | Value |")
        lines.append(f"|----------|-------|")
        lines.append(f"| Thrust | {burn.thrust_n:.1f} N ({burn.thrust_n/1000:.2f} kN) |")
        lines.append(f"| ṁ | {burn.mdot_kg_s:.4f} kg/s |")
        lines.append(f"| Burn time | {burn.burn_time_s:.2f} s |")
        lines.append(f"| Total impulse | {burn.total_impulse_n_s:.0f} N·s |")
        lines.append("")

    if nozzle and nozzle.success:
        lines.append("## Nozzle / chamber geometry (1-D estimate)")
        lines.append("")
        lines.append(f"| Quantity | Value |")
        lines.append(f"|----------|-------|")
        lines.append(f"| At | {nozzle.throat_area_m2*1e4:.3f} cm² ({nozzle.throat_area_m2:.6e} m²) |")
        lines.append(f"| Dt | {nozzle.throat_diameter_m*1000:.2f} mm |")
        lines.append(f"| Ae | {nozzle.exit_area_m2*1e4:.3f} cm² |")
        lines.append(f"| De | {nozzle.exit_diameter_m*1000:.2f} mm |")
        if nozzle.chamber_volume_m3 is not None:
            lines.append(f"| Vc (L*={nozzle.lstar_m} m) | {nozzle.chamber_volume_m3*1e6:.1f} cm³ |")
        lines.append("")

    if tank_volumes:
        lines.append("## Tank volume estimate (ullage included)")
        lines.append("")
        lines.append(f"| Quantity | Value |")
        lines.append(f"|----------|-------|")
        lines.append(f"| m fuel | {tank_volumes['m_fuel_kg']:.2f} kg |")
        lines.append(f"| m oxidizer | {tank_volumes['m_oxidizer_kg']:.2f} kg |")
        lines.append(f"| V fuel | {tank_volumes['v_fuel_L']:.2f} L |")
        lines.append(f"| V oxidizer | {tank_volumes['v_oxidizer_L']:.2f} L |")
        lines.append("")

    if comparisons:
        lines.append("## Nearby real engines (open literature, approximate)")
        lines.append("")
        lines.append("| Engine | Ref Isp [s] | ΔIsp [s] | Cycle |")
        lines.append("|--------|-------------|----------|-------|")
        for c in comparisons:
            lines.append(
                f"| {c['name']} | {c['ref_isp_s']:.1f} | {c['delta_isp_s']:+.1f} | {c['cycle']} |"
            )
        lines.append("")
        lines.append("_Comparison is educational only; duty cycle and nozzle differ._")
        lines.append("")

    if extra_notes:
        lines.append("## Notes")
        lines.append("")
        lines.append(extra_notes)
        lines.append("")

    lines.append("---")
    lines.append("RocketCAE · NASA CEA thermodynamics · ideal sizing helpers")
    return "\n".join(lines)


def write_design_brief(path: str | Path, content: str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
